### ISSUE TITLE
Leftover calls of disable_all_triggers

### ISSUE THREAD

**Issue by bl0x** [flueke/mesytec-mvlc#2]
The function was renamed and there are some references left over from before the refactor:

extras/mvlc-ctrl-tests/mvlc_ctrl_test_stack_executor.cc:31:        if (auto ec = disable_all_triggers(mvlc))
extras/mvlc-ctrl-tests/mvlc_ctrl_test_stack_executor.cc:138:        if (auto ec = disable_all_triggers(mvlc))
extras/mvlc-ctrl-tests/mvlc_ctrl_test_stack_executor.cc:231:        if (auto ec = disable_all_triggers(mvlc))
extras/mvlc-ctrl-tests/mvlc_ctrl_test_stack_executor.cc:342:        if (auto ec = disable_all_triggers(mvlc))
src/mesytec-mvlc/mvlc_impl_usb.cc:352:    ec = f.get(); // wait here for disable_all_triggers() to complete

**Comment by flueke** [comment]
I've pushed the latest local commits to github today and it seems this issue was fixed at some point.
