### ISSUE TITLE
Compilation problem using mesytec-mvlc: fatal error: argh.h: No such file or directory

### ISSUE THREAD

**Issue by jdfrankland** [flueke/mesytec-mvlc#4]
Hi Florian
I built & installed the main branch as a stand-alone package (outside of mvme package) on my Ubuntu laptop
and then tried to compile https://gitlab.in2p3.fr/mesytec-ganil/mesytec_data using the mesytec-mvlc::mesytec-mvlc
CMake target (which has always worked when mesytec-mvlc is installed as part of mvme).

The problem is:
In file included from /home/frankland/software/install/include/mesytec-mvlc/mesytec-mvlc.h:37,
                 from /home/frankland/software/sources/mesytec_data/lib/mesytec_buffer_reader_mvlc_parser.h:4,
                 from /home/frankland/software/sources/mesytec_data/lib/mesytec_buffer_reader_mvlc_parser.cpp:1:
/home/frankland/software/install/include/mesytec-mvlc/mvlc_factory.h:31:10: fatal error: argh.h: No such file or directory
   31 | #include <argh.h>

argh.h is installed by mesytec-mvlc in include/mesytec-mvlc, so it's a question of include paths.

I have found a workaround, I don't know if it may have side-effects:
modify the INSTALL_INTERFACE include directory in external/argh/CMakeLists.txt: line 35
target_include_directories(argh .... $<INSTALL_INTERFACE:include/mesytec-mvlc>)

Cheers
John

**Comment by flueke** [comment]
Hello John,
the issue should be fixed in 64be543893c4a0834308a4a10c5d7b87b54d8635.
Thank you for reporting this!

**Comment by jdfrankland** [comment]
OK so I clicked the wrong button... Should be closed now!
